runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: warn
site:
  title: Dev Docs
  url: https://zhanliquan.github.io/dev-docs
  start_page: spring-cloud::index.adoc
  robots: allow
content:
  sources:
  - url: /home/zlq/Production/GitRepos/spring-cloud.git
    branches: master

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./docs